version: '3.3'

services:
  stable-diffusion:
    container_name: sd-webui
    image:  stable-diffusion-webui:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - ../sd-models:/sd/models_external
      - ../sd-outputs:/sd/outputs
      - ../sd-cache/model_cache:/sd/model_cache
      - ../sd-cache/root_profile:/root
    ports:
      - '7861:7860'
      - '8501:8501'
    healthcheck:
      test: curl --fail http://localhost:8501 --head || curl --fail http://localhost:7860 --head || echo 1
      interval: 30s
      timeout: 1s
      retries: 10
    devices:
      - "/dev/kfd"
      - "/dev/dri"